### ISSUE TITLE
Architecture: domain class Clone has a reference to infrastructure class CodeBaseAlreadyExistsException

### ISSUE THREAD

**Issue by lolo101** [salimchami/historyscan#54]
**Describe the bug**
In the hexagonal architecture, It is forbidden for the domain to have a dependency on the infrastructure

**Expected behavior**
Domain is self-contained

**Comment by lolo101** [comment]
Idem for CodeBaseCloner & CodeBaseRepository classes

**Comment by salimchami** [comment]
the project should contain archunit to test thins things...
