### ISSUE TITLE
Navbar title is missing in the translation file

### ISSUE THREAD

**Issue by lolo101** [salimchami/historyscan#55]
**Describe the bug**
The navbar title is missing in the i18n file. As a consequence, the translation key shows up instead of a neat title

**To Reproduce**
Just open the front in the browser

**Expected behavior**
A neat title is visible

**Screenshots**
![image](https://github.com/salimchami/historyscan/assets/555864/0daa47f1-817a-4573-8d7b-1caa302988c6)

**Comment by salimchami** [comment]
fixed ! thanks :-)
